version: "3"

services:
    terraform:
        build:
            context: .
            args:
              ALPINE_IMAGE: ${ALPINE_IMAGE}
              TERRAFORM_VERSION: ${TERRAFORM_VERSION}
              container_name: tfbuilder
        environment:
            - TF_VAR_aws_access_key=${AWS_ACCESS_KEY_ID}
            - TF_VAR_aws_secret_key=${AWS_SECRET_ACCESS_KEY}
            - TF_VAR_aws_default_region=${AWS_DEFAULT_REGION}
        command: ./run.sh